config/routes.rb
Rails.application.routes.draw do
  get 'webhook/notifications'

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  resources :ragios_monitors do
    collection do
      get :events
      get :find
      post :test
      put :start
      put :stop
    end
  end

  resources :maestro, only: :none do
    collection do
      post :validate
      post :test
    end
  end

  resources :webhook, only: :none do
    collection do
      post :notifications
    end
  end

  resources :email_notifiers, only: [:create, :destroy] do
    collection do
      get :verification
    end
  end

  resources :guest_monitor, only: [:create]

  resources :dashboard, only: [:index] do
    member do
      get :monitor
    end
    collection do
      get :notifications
    end
  end

  get 'pages/home'

  get 'pages/about'

  get 'pages/doc'

  get 'pages/contact_us'

  get 'pages/how_it_works'

  devise_for :users, controllers: { registrations: "registrations" }

  devise_scope :user do
    get "/signin" => "devise/sessions#new"
  end

  devise_scope :user do
    get "/signup" => "devise/registrations#new"
  end

  authenticated :user do
    root to: "dashboard#index", as: :authenticated_root
  end
  unauthenticated do
    root to: "pages#home", as: :unauthenticated_root
  end

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_filter :authenticate_user!

  def index
    @active_monitors = current_user.cached_active_monitors
    @monitors = current_user.cached_monitors
    add_breadcrumb "All Monitors", dashboard_index_path
  end

  def notifications
    @email_notifiers = current_user.cached_email_notifiers
    add_breadcrumb "All Monitors", dashboard_index_path
    add_breadcrumb "Notifications", notifications_dashboard_index_path
  end

  def monitor
    @monitor = current_user.cached_monitor(params[:id])
    @email_notifiers = current_user.cached_verified_email_notifiers
    @current_alert_emails = @monitor.cached_email_notifiers.map(&:email)
    add_breadcrumb "All Monitors", dashboard_index_path
    add_breadcrumb @monitor.title.to_s, monitor_dashboard_path
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
  def monitor_status(status, ragiosid, active_monitors)
    if status == RagiosMonitor.status(:cannot_create)
      '<span class="label alert">Could not create Monitor</span>'
    elsif status == RagiosMonitor.status(:active)
      m = active_monitors.detect { |i| i[:_id] == ragiosid }
      if m
        if m[:status_] == "active"
          ("<span class=\"label info\">active</span>").html_safe
        elsif m[:status_] == "stopped"
          ("<span class=\"label warning\">stopped</span>").html_safe
        else
          ("<span class=\"label secondary\">#{m[:status_]}</span>").html_safe
        end
      else
        ('<span class="label alert">unknown</span>').html_safe
      end
    elsif status == RagiosMonitor.status(:pending)
      ('<span class="label secondary">pending</span>').html_safe
    end
  end

  def checked(email_notifier, current_notifiers_list)
    current_notifiers_list.include?(email_notifier.email) ? "checked" : ""
  end

  def monitor_type(type)
    if type == RagiosMonitor::TYPE[:http_check]
      "HTTP Check"
    elsif type == RagiosMonitor::TYPE[:real_browser_monitor]
      "Real Browser Monitor"
    end
  end
end

app/views/dashboard/index.html.erb
<div class="row">
  <div class="column">
    <ul class="breadcrumbs">
      <%= render_breadcrumbs :tag => :li, :separator => "" %>
    </ul>
  </div>
</div>
<div class="row">
  <div class="column">
    <% flash.each do |key, value| %>
      <div data-alert class="alert-box <%= key %>">
        <div><%= value %></div>
        <a href="#" class="close">&times;</a>
      </div>
    <% end %>
  </div>
</div>
<div class="row">
  <div class="column">
    <div class="panel">
      <a href="<%= new_ragios_monitor_path %>" class="button tiny"><i class="fi-plus icon"></i>Add New Monitor</a>
    </div>
  </div>

  <div class="column">
    <table width="100%">
      <thead>
        <tr>
          <th>Monitor</th>
          <th>URL</th>
          <th>Every</th>
          <th>Type</th>
          <th>Status</th>
          <th>Actions<th>
        </tr>
      </thead>
      <tbody>
        <% unless @monitors.blank? %>
          <% @monitors.each do |monitor| %>
            <tr>
              <td><%= link_to monitor.title, monitor_dashboard_path(monitor) %></td>
              <td><%= link_to monitor.url, monitor_dashboard_path(monitor) %></td>
              <td><%= "#{monitor.hours} hours, #{monitor.minutes} minutes" %></td>
              <td><%= monitor_type(monitor.monitor_type) %></td>
              <td><%= monitor_status(monitor.status.to_i, monitor.ragiosid, @active_monitors) %></td>
              <td>
                <%= link_to "<i class=\"fi-trash\"></i>".html_safe, ragios_monitor_path(monitor), title: "Delete this monitor", data: {confirm: "Are you sure you want to delete the monitor: (#{monitor.title})?"}, method: :delete %>
              </td>
            </tr>
          <% end %>
        <% else %>
          <tr>
            <td>You have no monitors. Add your first monitor <a href="<%= new_ragios_monitor_path %>">start here</a></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/dashboard/monitor.html.erb
<%= javascript_include_tag "monitor" %>
<span id="maestro-info" data-maestro-url="<%= validate_maestro_index_path %>" data-maestro-test-url="<%= test_maestro_index_path %>"></span>
<span class="hide" id="monitor-info" data-monitor-id="<%= @monitor.ragiosid %>"
  data-events-url="<%= events_ragios_monitors_path(ragios_id: @monitor.ragiosid) %>"
  data-find-monitor-url="<%= find_ragios_monitors_path(id: @monitor.id, ragios_id: @monitor.ragiosid) %>"
  data-test-url="<%= test_ragios_monitors_path(ragios_id: @monitor.ragiosid) %>"
  data-start-url="<%= start_ragios_monitors_path(ragios_id: @monitor.ragiosid) %>"
  data-stop-url="<%= stop_ragios_monitors_path(ragios_id: @monitor.ragiosid) %>"
  data-restful-url="<%= ragios_monitor_path(@monitor.id) %>"
  data-dashboard-url="<%= dashboard_index_path %>"
  data-is-uptime-monitor="<%= (@monitor.monitor_type == "uptime_monitor") %>">
</span>
<div class="row">
  <div class="column">
    <ul class="breadcrumbs">
      <%= render_breadcrumbs :tag => :li, :separator => "" %>
    </ul>
  </div>
</div>
<div class="row">
  <div class="columns">
    <span id="message"></span>
    <script id="message-template" type="text/template">
    <div data-alert class="alert-box {{= alert }}">
      <div>{{= message }}!</div>
      <div>{{= response }}</div>
      <a href="#" class="close">&times;</a>
    </div>
    </script>
  </div>
</div>

<div class="row">
  <div class="column">
    <div class="panel">
      <ul class="tabs" id="monitor-tab" data-tabs>
        <li id="monitors-tab" class="tabs-title is-active"><a id="monitor-link" data-tabs-target="monitor" aria-selected="true" href="#monitor"><i class="fi-widget icon"></i>Monitor</a></li>
        <li id="all-events-tab" class="tabs-title"><a id="all-events-link" data-tabs-target="all-events" href="#all-events"><i class="fi-graph-trend icon"></i>Events</a></li>
      </ul>
      <div class="tabs-content" data-tabs-content="monitor-tab">
        <div class="tabs-panel is-active" id="monitor">
          <div class="row">
            <div class="column">
              <form id="monitor-form">
                <span id="monitor-details"></span>
                <script id="monitor-details-template" type="text/template">
                  <div class="row">
                    <div class="medium-6 columns">
                      <label>Title
                        <input type="text" name="title" value="{{= monitor }}" />
                      </label>
                    </div>
                    <div class="medium-6 columns">
                      <label>URL
                        <input type="text" name="url" id="url" value="{{= url }}" />
                      </label>
                    </div>
                  </div>
                  <div class="row">
                    <div class="columns medium-6">
                      <label>This monitor runs every:
                        <div class="row">
                          <div class="columns small-6">
                            <label>Hours
                              <input type="number" name="hours" placeholder="0" value="{{= hours }}"  min="0" />
                            </label>
                          </div>
                          <div class="columns small-6">
                            <label>Minutes
                              <input type="number" name="minutes" value="{{= minutes }}"  min="0" />
                            </label>
                          </div>
                        </div>
                      </label>
                    </div>
                    <div class="columns medium-6">
                      <div class="row">
                        <div class="columns">
                          State: {{= ragiosHelper.formatState(current_state_.state) }}
                        </div>
                      </div>
                      <div class="row">
                        <div class="columns">
                          Status: {{= ragiosHelper.formatState(status_) }}
                        </div>
                      </div>
                    </div>
                  </div>
                </script>
                <div class="row">
                  <div class="columns">
                    <% if @email_notifiers.blank? %>
                      You have not add an alert email, add alert emails <%= link_to "here", notifications_dashboard_index_path %>
                    <% else %>
                      <label>Send Email alerts to:</label>
                      <% @email_notifiers.each do |n| %>
                        <input id="alert_emails_<%=n.id%>" class="alert-emails" name="alert_emails" type="checkbox" value="<%= n.email %>"  <%= checked(n, @current_alert_emails) %>><label for="alert_emails_<%=n.id%>"><%= n.email %></label>
                      <% end %>
                    <% end %>
                  </div>
                </div>
                <% if @monitor.monitor_type == RagiosMonitor::TYPE[:real_browser_monitor] %>
                  <div class="row">
                    <div class="columns">
                      <div id="validations">
                        <textarea id="source-code" name="source_code" class="hide"></textarea>
                        <div class="row">
                          <div class="columns">
                            <label>Validations & Actions<br/>
                              <div id="editor" name="code"></div>
                            </label>
                            <span id="console"></span>
                            <script id="syntax-error-template" type="text/template">
                              <div id="syntax-error" class="search-results">{{= error }}</div>
                            </script>
                            <script id="results-template" type="text/template">
                              {{ _.each( results, function(i) { }}
                                <div id="results" class="search-results">{{if (i[0] === "error") {  }}{{= i[1] }}{{ } }}{{ if (i[0] !== "error") { }} ({{= _.indexOf(results, i) + 1 }}.) {{ } }} {{ if (i[1] === "exists_as_expected") { }} {{= i[0] }} <span class="label success">exists as expected</span>{{ } else if (i[1] === "does_not_exist_as_expected") {  }} {{= i[0] }} <span class="label alert">does not exists as expected</span>{{ } }}</div>
                              {{ }); }}
                            </script>
                            <%= render "shared/loading_effect" %>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                <% end %>
                <div class="row" style="margin-top:15px;">
                  <div class="columns">
                    <% if @monitor.monitor_type == RagiosMonitor::TYPE[:real_browser_monitor] %>
                      <a id="test-monitor" class="button tiny monitor-actions"><i class="fi-wrench icon"></i>Run Script</a>
                    <% end %>
                    <a id="update-monitor-button" href="#" class="button tiny"><i class="fi-save icon"></i>Update Monitor</a>
                    <a id="test-button" href="#" class="button tiny"><i class="fi-results icon"></i>Test Monitor</a>
                    <a id="start-button" href="#" class="button tiny"><i class="fi-play icon"></i>Start Monitor</a>
                    <a id="stop-button" href="#" class="button tiny"><i class="fi-stop icon"></i>Stop Monitor</a>
                    <a id="delete-button" href="#" class="button tiny"><i class="fi-trash icon"></i>Delete Monitor</a>
                  </div>
                </div>
              </form>
            </div>
          </div>
        </div>
        <div class="tabs-panel content" id="all-events">
          <div class="row">
            <div class="columns">
              <table  id="all-events-datatable" >
                <thead>
                  <tr>
                    <th>Time</th>
                    <th>Event Type</th>
                    <th>State</th>
                    <th>Result</th>
                  </tr>
                </thead>
                <tbody>
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/dashboard/notifications.html.erb
<%= javascript_include_tag "notifications" %>
<div class="row">
  <div class="column">
    <ul class="breadcrumbs">
      <%= render_breadcrumbs :tag => :li, :separator => "" %>
    </ul>
  </div>
</div>

<div class="row">
  <div class="column">
    <% flash.each do |key, value| %>
      <div data-alert class="alert-box <%= key %>">
        <div><%= value %></div>
        <a href="#" class="close">&times;</a>
      </div>
    <% end %>
  </div>
</div>

<div class="row">
  <div class="column medium-8">
    <div class="panel">
      <h3> Alert Emails</h3>
      <table width="100%">
        <thead>
          <tr>
            <th>Email</th>
            <th>Status</th>
            <th>Actions</th>
          </tr>
        </thead>
        <tbody>
          <% if @email_notifiers.blank? %>
            <tr>
              <td>There are no alert emails</td>
            </tr>
          <% else %>
            <% @email_notifiers.each do |n| %>
              <tr>
                <td><%= n.email %></td>
                <td><%= n.verified ? "verified" : "Awaiting verification" %></td>
                <td>
                  <%= link_to "<i class=\"fi-trash\"></i>".html_safe, email_notifier_path(n), title: "Delete this alert email", data: {confirm: "Are you sure you want to delete this email (#{n.email})?"}, method: :delete %>
                </td>
              </tr>
            <% end %>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
  <div class="column medium-4">
    <div class="panel">
      <%= form_tag email_notifiers_path, method: :post, data: {abide: ''} %>
        <div class="row">
          <div class="columns">
            <label>Add New Email <small>required</small>
              <input type="email" name="email" required>
            </label>
            <small class="error">A valid Email Address is required.</small>
          </div>
        </div>
        <div class="row">
          <div class="columns">
            <button class="button tiny" type="submit"><i class="fi-plus icon"></i>Submit</button>
          </div>
        </div>
      </form>
    </div>
  </div>
</div>