config/routes.rb
Rails.application.routes.draw do
  get 'webhook/notifications'

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  resources :ragios_monitors do
    collection do
      get :events
      get :find
      post :test
      put :start
      put :stop
    end
  end

  resources :maestro, only: :none do
    collection do
      post :validate
      post :test
    end
  end

  resources :webhook, only: :none do
    collection do
      post :notifications
    end
  end

  resources :email_notifiers, only: [:create, :destroy] do
    collection do
      get :verification
    end
  end

  resources :guest_monitor, only: [:create]

  resources :dashboard, only: [:index] do
    member do
      get :monitor
    end
    collection do
      get :notifications
    end
  end

  get 'pages/home'

  get 'pages/about'

  get 'pages/doc'

  get 'pages/contact_us'

  get 'pages/how_it_works'

  devise_for :users, controllers: { registrations: "registrations" }

  devise_scope :user do
    get "/signin" => "devise/sessions#new"
  end

  devise_scope :user do
    get "/signup" => "devise/registrations#new"
  end

  authenticated :user do
    root to: "dashboard#index", as: :authenticated_root
  end
  unauthenticated do
    root to: "pages#home", as: :unauthenticated_root
  end

end

app/views/pages/_form.html.erb
<%= form_for(@guest_monitor, url: guest_monitor_index_path, method: :post, html: {id: "new_guest_monitor" , data: { abide: '' }}) do |f| %>
  <% if @guest_monitor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ragios_monitor.errors.count, "error") %> prohibited this ragios_monitor from being saved:</h2>
      <ul>
        <% @guest_monitor.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="columns small-6">
      <label>Fill in URL <small>required</small>
        <input id="url" type="text" name="url" value="<%= @guest_monitor.url %>" required>
      </label>
      <small class="error">A URL is required</small>
    </div>
  </div>

  <div id="validations">
    <textarea id="source-code" name="source_code" class="hide"></textarea>
    <div class="row">
      <div class="columns">
        <label>Fill in Validations & Actions<br/>
          <div id="editor" name="code"></div>
        </label>
        <span id="console"></span>
        <script id="syntax-error-template" type="text/template">
          <div id="syntax-error" class="search-results">{{= error }}</div>
        </script>
        <script id="results-template" type="text/template">
          {{ _.each( results, function(i) { }}
            <div id="results" class="search-results">{{if (i[0] === "error") {  }}{{= i[1] }}{{ } }}{{ if (i[0] !== "error") { }} ({{= _.indexOf(results, i) + 1 }}.) {{ } }} {{ if (i[1] === "exists_as_expected") { }} {{= i[0] }} <span class="label success">exists as expected</span>{{ } else if (i[1] === "does_not_exist_as_expected") {  }} {{= i[0] }} <span class="label alert">does not exists as expected</span>{{ } }}</div>
          {{ }); }}
        </script>
        <%= render "shared/loading_effect" %>
      </div>
    </div>
  </div>

  <div class="row" style="margin-top:15px;">
    <div class="columns">
      <a id="test-monitor" class="button tiny monitor-actions"><i class="fi-wrench icon"></i>Run Script</a>
      <a id="submit-monitor" class="button tiny monitor-actions"><i class="fi-arrow-right icon"></i>Save & Continue</a>
    </div>
  </div>
<% end %>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/contact_us.html.erb
<h1>Pages#contact_us</h1>
<p>Find me in app/views/pages/contact_us.html.erb</p>

app/views/pages/doc.html.erb
<h1>Pages#doc</h1>
<p>Find me in app/views/pages/doc.html.erb</p>

app/views/pages/home.html.erb
<%= javascript_include_tag "guest_monitor" %>
<span id="maestro-info" data-maestro-url="<%= validate_maestro_index_path %>" data-maestro-test-url="<%= test_maestro_index_path %>" data-source-code="<%= @guest_monitor.code %>"></span>
<section id="header">
  <div class="row">
    <div class="column">
      <h1>Maestro</h1>
    </div>
  </div>
</section>
<section id="sub-header">
  <div class="row">
    <div class="column medium-6">
      <p class="caption">Monitor your website with actions & validations like a real user</p>
      <p class="caption">Our automated web browser (firefox & Chrome) will run your validations & actions</p>
      <p class="caption">Set time intervals to run your valiadations and actions</p>
    </div>
    <div class="column medium-6">
      <p class="caption">Discover errors before your users</p>
      <p class="caption">Receive screenshots when we detect an error</p>
      <p class="caption">Register <%= link_to "here", new_user_registration_path %></p>
    </div>
  </div>
</section>
<section id="start-here">
  <div class="row">
    <div class="column">
      <h5>Try it here</h5>
    </div>
  </div>
  <div class="row">
    <div class="columns">
      <div class="panel">
        <%= render 'form' %>
      </div>
    </div>
  </div>
</section>

app/views/pages/how_it_works.html.erb
<h1>Pages#how_it_works</h1>
<p>Find me in app/views/pages/how_it_works.html.erb</p>