config/routes.rb
Rails.application.routes.draw do
  get 'webhook/notifications'

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  resources :ragios_monitors do
    collection do
      get :events
      get :find
      post :test
      put :start
      put :stop
    end
  end

  resources :maestro, only: :none do
    collection do
      post :validate
      post :test
    end
  end

  resources :webhook, only: :none do
    collection do
      post :notifications
    end
  end

  resources :email_notifiers, only: [:create, :destroy] do
    collection do
      get :verification
    end
  end

  resources :guest_monitor, only: [:create]

  resources :dashboard, only: [:index] do
    member do
      get :monitor
    end
    collection do
      get :notifications
    end
  end

  get 'pages/home'

  get 'pages/about'

  get 'pages/doc'

  get 'pages/contact_us'

  get 'pages/how_it_works'

  devise_for :users, controllers: { registrations: "registrations" }

  devise_scope :user do
    get "/signin" => "devise/sessions#new"
  end

  devise_scope :user do
    get "/signup" => "devise/registrations#new"
  end

  authenticated :user do
    root to: "dashboard#index", as: :authenticated_root
  end
  unauthenticated do
    root to: "pages#home", as: :unauthenticated_root
  end

end

app/models/ragios_monitor.rb
class RagiosMonitor < ActiveRecord::Base
  belongs_to :user
  has_many :email_notifiers

  after_commit :flush_cache

  STATUSES = %w(pending active cannot_create)

  TYPE = {
    http_check: "url_monitor",
    real_browser_monitor: "uptime_monitor"
  }.freeze

  def self.status(value)
    STATUSES.index(value.to_s)
  end

  def self.client
    @ragios_client ||= Ragios::Client.new(
      username: ENV["RAGIOS_SERVER_USERNAME"],
      password: ENV["RAGIOS_SERVER_PASSWORD"],
      address: ENV["RAGIOS_SERVER_URL"],
      port: ENV["RAGIOS_SERVER_PORT"]
    )
  end

  def self.cached_expire_in(ragiosid)
    Rails.cache.fetch("monitor_#{ragiosid}_expire_in") do
      monitor = RagiosMonitor.where(ragiosid: ragiosid).first
      if monitor
        ((monitor.hours * 60 * 60) + (monitor.minutes * 60)) - 5
      end
    end
  end

  def cached_email_notifiers
    Rails.cache.fetch([self.class.name, id, :email_notifiers], expires_in: 240.hours) do
      self.email_notifiers.to_a
    end
  end


  def flush_cache
    Rails.cache.delete([self.user.class.name, self.user_id, :active_monitors])
    Rails.cache.delete([self.user.class.name, self.user_id, :monitors])
    Rails.cache.delete([self.user.class.name, self.user_id, self.id, :monitor])
    Rails.cache.delete([self.user.class.name, self.user_id, self.ragiosid, :find_monitor])
    Rails.cache.delete([self.user.class.name, self.user_id, self.ragiosid, :event_expires_in])
    Rails.cache.delete([self.user.class.name, self.user_id, self.ragiosid, :monitor_events])
    Rails.cache.delete([self.user.class.name, self.user_id, self.ragiosid, :ragios_monitor])
  end
end

app/controllers/ragios_monitors_controller.rb
class RagiosMonitorsController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_ragios_monitor, only: [:edit, :update, :show, :find, :destroy]
  before_action :set_client, only: [:events, :find, :test, :stop, :start, :update, :destroy]
  before_action :touch_monitor, only: [:test, :stop, :start]

  # GET /ragios_monitors
  def index
  end

  # GET /ragios_monitors/1
  def show
  end

  # GET /ragios_monitors/new
  def new
    guest = User.find_by_id(session[:guest_user_id])
    @ragios_monitor = guest&.ragios_monitors&.first || RagiosMonitor.new

    if guest
      flash[:info] = "Fill in the remaining fields and submit"
      guest.ragios_monitors.destroy_all
      guest.destroy
      session.delete(:guest_user_id)
    end

    @alert_emails = current_user.email_notifiers.where(verified: true)
    add_breadcrumb "All Monitors", dashboard_index_path
    add_breadcrumb "Add New Monitor", new_ragios_monitor_path
  end

  # GET /ragios_monitors/1/edit
  def edit
  end

  def find
    response = current_user.cached_find_monitor(params[:ragios_id])
    render json: response.to_json
  rescue Ragios::ClientException => e
    m = {error: e.message}
    render json: m.to_json, status: 500
  end

  # POST /ragios_monitors
  def create
    @ragios_monitor = RagiosMonitor.new(
      url: params[:url],
      title: params[:title],
      hours: params[:hours].to_i,
      minutes: params[:minutes].to_i
    )
    @ragios_monitor.monitor_type =
    if params[:monitor_type].to_sym == :http_check
      "url_monitor"
    elsif params[:monitor_type].to_sym == :real_browser_monitor
      "uptime_monitor"
    end
    @ragios_monitor.user = current_user
    @ragios_monitor.code = params[:source_code] if params[:monitor_type].to_sym == :real_browser_monitor


    if @ragios_monitor.save
      MonitorCreationJob.perform_later(@ragios_monitor.id, webhook_notifications_url)
      add_email_notifiers
      redirect_to dashboard_index_path, info: 'The monitor was successfully created.'
    else
      render :new
    end
  end

  def stop
    response = @client.stop(params[:ragios_id])
    render json: response.to_json
  end

  def test
    response = @client.test(params[:ragios_id])
    render json: response.to_json
  end

  def start
    response = @client.start(params[:ragios_id])
    render json: response.to_json
  end

  def events
    response = current_user.cached_monitor_events(params[:ragios_id])
    render json: response.to_json
  end

  # PATCH/PUT /ragios_monitors/1
  def update
    response = @client.update(
      @ragios_monitor.ragiosid,
      url: params[:url],
      every: "#{params[:hours]}h#{params[:minutes]}m",
      monitor: params[:title],
      exists?: params[:source_code]
    )
    @ragios_monitor.reload.update(ragios_monitor_params)
    add_email_notifiers
    render json: response.to_json
  end

  # DELETE /ragios_monitors/1
  def destroy
    response = @client.delete(@ragios_monitor.ragiosid)
    @ragios_monitor.destroy
    render json: response.to_json
  end

  private
    def add_email_notifiers
      if params[:alert_emails]
        notifiers = EmailNotifier.where(email: params[:alert_emails], verified: true)
        @ragios_monitor.email_notifiers = notifiers
      else
        @ragios_monitor.email_notifiers = []
      end
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_ragios_monitor
      @ragios_monitor = current_user.cached_monitor(params[:id])
    end

    def set_client
      @client ||= RagiosMonitor.client
    end

    def touch_monitor
      monitor = current_user.cached_ragios_monitor(params[:ragios_id])
      if monitor
        monitor.touch
        true
      else
        false
      end
    end

    # Only allow a trusted parameter "white list" through.
    def ragios_monitor_params
      params.require(:ragios_monitor).permit(:title, :description, :url, :hours, :minutes, :ragiosid, :string, :code, :type, :monitor_json, :user_id)
    end
end

app/helpers/ragios_monitors_helper.rb
module RagiosMonitorsHelper
end

app/views/ragios_monitors/_form.html.erb
<%= form_for(@ragios_monitor, html: { data: { abide: '' }}) do |f| %>
  <% if @ragios_monitor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ragios_monitor.errors.count, "error") %> prohibited this ragios_monitor from being saved:</h2>
      <ul>
        <% @ragios_monitor.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="columns small-6">
      <label>Title <small>required</small>
        <input type="text" name="title" required>
      </label>
      <small class="error">A Title is required.</small>
    </div>
    <div class="columns small-6">
      <label>URL <small>required</small>
        <input id="url" type="text" name="url" value="<%= @ragios_monitor.url %>" required>
      </label>
      <small class="error">A URL is required</small>
    </div>
  </div>

  <div class="row">
    <div class="columns medium-6">
      <label>Run this monitor every?
        <div class="row">
          <div class="columns small-6">
            <label>Hours
              <input type="number" name="hours" placeholder="0"  min="0" />
            </label>
          </div>
          <div class="columns small-6">
            <label>Minutes
              <input type="number" name="minutes" value="5"  min="0" />
            </label>
          </div>
        </div>
      </label>
    </div>
    <div class="columns medium-6">
      <label>Monitor Type</label>
      <input type="radio" name="monitor_type" value="http_check" id="http_check"><label for="http_check">HTTP check</label>
      <input type="radio" name="monitor_type" value="real_browser_monitor" id="real_browser_monitor" checked="checked"><label for="real_browser_monitor">Real Browser Monitor</label>
    </div>
  </div>

  <div class="row">
    <div class="columns">
      <% if @alert_emails.blank? %>
        You have not added an alert email, add alert emails <%= link_to "here", notifications_dashboard_index_path %>
      <% else %>
        <label>Send Email alerts to:</label>
        <% @alert_emails.each do |n| %>
          <input id="alert_emails_<%=n.id%>" name="alert_emails[]" type="checkbox" value="<%= n.email %>"><label for="alert_emails_<%=n.id%>"><%= n.email %></label>
        <% end %>
      <% end %>
    </div>
  </div>

  <div id="validations">
    <textarea id="source-code" name="source_code" class="hide"></textarea>
    <div class="row">
      <div class="columns">
        <label>Fill in Validations & Actions<br/>
          <div id="editor" name="code"></div>
        </label>
        <span id="console"></span>
        <script id="syntax-error-template" type="text/template">
          <div id="syntax-error" class="search-results">{{= error }}</div>
        </script>
        <script id="results-template" type="text/template">
          {{ _.each( results, function(i) { }}
            <div id="results" class="search-results">{{if (i[0] === "error") {  }}{{= i[1] }}{{ } }}{{ if (i[0] !== "error") { }} ({{= _.indexOf(results, i) + 1 }}.) {{ } }} {{ if (i[1] === "exists_as_expected") { }} {{= i[0] }} <span class="label success">exists as expected</span>{{ } else if (i[1] === "does_not_exist_as_expected") {  }} {{= i[0] }} <span class="label alert">does not exists as expected</span>{{ } }}</div>
          {{ }); }}
        </script>
        <%= render "shared/loading_effect" %>
      </div>
    </div>
  </div>

  <div class="row" style="margin-top:15px;">
    <div class="columns">
      <a id="test-monitor" class="button tiny monitor-actions"><i class="fi-wrench icon"></i>Run Script</a>
      <a id="submit-monitor" href="#" class="button tiny monitor-actions"><i class="fi-arrow-right icon"></i>Submit</a>
    </div>
  </div>
<% end %>

app/views/ragios_monitors/edit.html.erb
<h1>Editing Ragios Monitor</h1>

<%= render 'form' %>

<%= link_to 'Show', @ragios_monitor %> |
<%= link_to 'Back', ragios_monitors_path %>

app/views/ragios_monitors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Ragios Monitors</h1>

<table>
  <thead>
    <tr>
      <th>Created at</th>
      <th>Monitor</th>
      <th>URL</th>
      <th>Time Interval</th>
      <th>Type</th>
      <th colspan="3">Status</th>
    </tr>
  </thead>
  <tbody>
    <% @ragios_monitors.each do |ragios_monitor| %>
      <tr>
        <td><%= ragios_monitor.created_at %></td>
        <td><%= ragios_monitor.title %></td>
        <td><%= ragios_monitor.url %></td>
        <td><%= ragios_monitor.time_interval %></td>
        <td><%= ragios_monitor.monitor_type %></td>
        <td><%= ragios_monitor.status.to_i %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ragios monitor', new_ragios_monitor_path %>

app/views/ragios_monitors/new.html.erb
<%= javascript_include_tag "new_monitors" %>
<span id="maestro-info" data-maestro-url="<%= validate_maestro_index_path %>" data-maestro-test-url="<%= test_maestro_index_path %>" data-source-code="<%= @ragios_monitor.code %>"></span>
<div class="row">
  <div class="column">
    <ul class="breadcrumbs">
      <%= render_breadcrumbs :tag => :li, :separator => "" %>
    </ul>
  </div>
</div>
<div class="row">
  <div class="column">
    <% flash.each do |key, value| %>
      <div data-alert class="alert-box <%= key %>">
        <div><%= value %></div>
        <a href="#" class="close">&times;</a>
      </div>
    <% end %>
  </div>
</div>
<div class="row">
  <div class="columns">
    <h5>Add New Monitor</h5>
  </div>
</div>
<div class="row">
  <div class="columns">
    <div class="panel">
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/ragios_monitors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @ragios_monitor.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @ragios_monitor.description %>
</p>

<p>
  <strong>Url:</strong>
  <%= @ragios_monitor.url %>
</p>

<p>
  <strong>Duration:</strong>
  <%= @ragios_monitor.duration %>
</p>

<p>
  <strong>Contact:</strong>
  <%= @ragios_monitor.contact %>
</p>

<p>
  <strong>Ragiosid:</strong>
  <%= @ragios_monitor.ragiosid %>
</p>

<p>
  <strong>String:</strong>
  <%= @ragios_monitor.string %>
</p>

<p>
  <strong>Code:</strong>
  <%= @ragios_monitor.code %>
</p>

<p>
  <strong>Type:</strong>
  <%= @ragios_monitor.type %>
</p>

<p>
  <strong>Monitor json:</strong>
  <%= @ragios_monitor.monitor_json %>
</p>

<p>
  <strong>User:</strong>
  <%= @ragios_monitor.user %>
</p>

<%= link_to 'Edit', edit_ragios_monitor_path(@ragios_monitor) %> |
<%= link_to 'Back', ragios_monitors_path %>